### ISSUE TITLE
Build fails in XCode 6.1 on Yosemite

### ISSUE THREAD

**Issue by phpguru** [jeromelebel/MongoHub-Mac#180]
Let me preface this by saying I'm new to Xcode but thought I'd try building the 3.0.8 release. Downloaded the .tgz.

When compiling for target 10.10:

```
/Users/phpguru/Downloads/MongoHub-Mac-3.0.8/Sources/MHPreferenceWindowController.m:189:9: 'NSBeginAlertSheet' is deprecated: first deprecated in OS X 10.10 - Use NSAlert instead
```

When compiling for target 10.9 or 10.8:

```
/Users/phpguru/Downloads/MongoHub-Mac-3.0.8/Sources/ConnectionWindow/MHQueryViewController.m:374:50: Class method '+convertObjectToJson:pretty:strictJson:' not found (return type defaults to 'id')
```

```
/Users/phpguru/Downloads/MongoHub-Mac-3.0.8/Sources/ConnectionWindow/MHQueryViewController.m:403:63: Class method '+convertObjectToJson:pretty:strictJson:' not found (return type defaults to 'id')
```

**Comment by ryandesign** [comment]
The problem remains, as originally stated. Please release a new stable version that does not have this problem.

**Comment by jeromelebel** [comment]
I still don't understand how MHPreferenceWindowController.m:189 can provide this error:
'NSBeginAlertSheet' is deprecated: first deprecated in OS X 10.10 - Use NSAlert instead

Since on the line, there is no call for NSBeginAlertSheet. Please provide a better explanation for the issue. 

Also, you need to know that 10.8 and 10.9 are supported. Therefore, NSBeginAlertSheet() is totally legitimate.

**Comment by ryandesign** [comment]
MHPreferenceWindowController.m:189 in version 3.0.8 (the latest stable version that appears to be available as of now) is:

```
NSBeginAlertSheet(@"Invalid Value", @"OK", nil, nil, self.window, nil, nil, nil, nil, @"The timeout should be greater than 500");
```

**Comment by jeromelebel** [comment]
This has been already fixed. Try top of the tree. Plus, as I said, there is no errors or warnings here, since MongoHub supports 10.8 and 10.9. Please make sure the OS X Deployment Target is set to 10.8.

**Comment by ryandesign** [comment]
Please release a new stable version containing the fix. Please support OS X deployment target 10.10.

**Comment by jeromelebel** [comment]
It will be stable when 3.1 will be stable. And why do you want me to drop support for 10.8? Just put "OS X deployment target" to 10.8 and "Base SDK" to 10.10.

**Comment by ryandesign** [comment]
I of course do not want you to drop support for 10.8.

**Comment by jeromelebel** [comment]
So I can't change "OS X deployment target" to 10.8

**Comment by ryandesign** [comment]
I'm not asking you to change the deployment target. I'm asking you to make it possible to build your code with the deployment target set to 10.10. Adding restrictions like 89d0a6679e0e22bcba5184f706d4b29d2b2b3af7 just limits the versions of OS X and Xcode that your code can be built on and makes it more difficult for potential contributors to build your code on their systems.

**Comment by jeromelebel** [comment]
I'm using 10.10 I don't understand your issue. deployment target is set to 10.8, base SDK is set to 10.10, and my system is 10.10. I can compile, I have no error, no warning. I do not use 10.8 on my computer.

**Comment by jeromelebel** [comment]
You are right, limitation on MAC_OS_X_VERSION_MAX_ALLOWED should not be useful. People with 10.8 or 10.9 should be able to compile MongoHub. Not only people with 10.10.
I've reverted that part: https://github.com/jeromelebel/MongoHub-Mac/commit/5a98ddb58005e462bf29587925c42e7c445d323d

**Comment by jeromelebel** [comment]
Or even with 10.11

**Comment by jeromelebel** [comment]
Did you find the solution to build MongoHub?

**Comment by jeromelebel** [comment]
by the way I don't really understand why someone would want/need to get MongHub with macports. I mean, this software depends on nothing, and there is a mechanism for a self-update.

**Comment by ryandesign** [comment]
You may be right that users do not need to install MongoHub with MacPorts. I just prefer to install software with MacPorts when possible, and now it is possible to install MongoHub 2.7b10 with MacPorts.

As a result of trying to add MongoHub to MacPorts, we uncovered some issues with your build system that made it more difficult for users to build from source, which they may want to do for other reasons, for example contributing to your project, or just modifying it for their own needs, and you were able to address those issues by making new versions of MongoHub from now on use a specific version of the libraries they depend on, so your builds are now repeatable. So in that sense I already consider adding MongoHub to MacPorts to have been worthwhile.

I haven't yet succeeded at building newer versions than 2.7b10, but I will certainly try it again after your next version with the build system improvements is released.

**Comment by jeromelebel** [comment]
I've done it several time to do a git clone git@github.com:jeromelebel/MongoHub-Mac.git and build.
The build downloads the sources and fails. The second works.

The issues I've just fixed are when a dev doesn't use git to get the source. Since I assumed people who wants to build MongoHub, are only contributors, therefore, I didn't spend too much time that, so far.
But I did fix those issues to help you.

I've discovered it is not possible to use xcodebuild without opening Xcode first. Maybe that's the issue you are having. I still don't know what is going on, on your side. I don't even know your settings.

I've just pushed: https://github.com/jeromelebel/MongoHub-Mac/commit/6a9fea2afacd812402df58ba8ef003aacc854d54 
And now using xcodebuild without opening Xcode works:
git clone git@github.com:jeromelebel/MongoHub-Mac.git
cd MongoHub-Mac
xcodebuild -configuration Debug -scheme MongoHub

**Comment by mahinthjoe** [comment]
Thanks
I successfully built using the above 3 statements on XCode6.1.1 Running on OSX 10.10.

Don't stop on a single build failure run 'xcodebuild -configuration Debug -scheme MongoHub'  multiple times (I had to do twice) if git is configured properly on your mac above script will automatically download the code from the respective git repository.

 Any tips on connecting to a remote mongodb via connection string at www.mongolab.com

**Comment by jeromelebel** [comment]
click on a mongodb:// link. It should work. Otherwise, you can read: https://github.com/jeromelebel/MongoHub-Mac/wiki/FAQ
